### ISSUE TITLE
[Question] Can s3fs be shared without mounting to host?

### ISSUE THREAD

**Issue by braco** [xueshanf/docker-s3fs#14]
Is it possible to mount the s3 volume in docker-compose and share with another service without mounting a shared volume on host?

In other words, something like this:

```
services:
  s3fs:
    image: xueshanf/s3fs:latest
    volumes:
      - s3fs:/mnt/s3fs
    command: /usr/bin/s3fs -o nonempty -f -o allow_other -o use_cache=/tmp ... /mnt/s3fs
  db:
    image: mariadb
    volumes:
      - s3fs:/tmp/s3
volumes:
  s3fs: {}
```

Where the expected behavior was the "db" service getting the s3 mount on /tmp/s3
