### ISSUE TITLE
Docker 1.10 can share volume with host now

### ISSUE THREAD

**Issue by philicious** [xueshanf/docker-s3fs#7]
Hi,
while evaluating some s3fs + docker questions, I came across your repo and your README seems outdated with v1.10 release in February.

See that guys post for more info https://abrv8.wordpress.com/2016/01/25/docker-1-10-shared-namespace-s3-fun/

Just wanted to let you know as your image is the most popular on DockerHub :+1: (according to pulls) and you might wanna update your readme.

**Comment by xueshanf** [comment]
Yay! I added usage instructions for Docker 1.10. Thank you!

**Comment by philicious** [comment]
Your welcome!
Good README for 1.10+ you did.

I'll play around with your image. However I need to share the s3fs mount as a volume with other container. I'll let you know how that went :)

**Comment by philicious** [comment]
@xueshanf as a followup: 
Defining the FUSE-mounted S3 folder as a docker volume (not as a shared host mount) and then linking it to other containers via `volumes-from` doesnt work.
However it does work if you share it with the host and then `volume` the host mount into other containers :tada: 

PS: Here you have a docker-compose service snippet for your image as I use it
(might be interesting for others also and for your README :wink:  )

```
  s3fs:
    image: xueshanf/s3fs:1.80
    environment:
      - AWSACCESSKEYID: FOOBAR
      - AWSSECRETACCESSKEY: FOOBARBAZ
    cap_add:
      - MKNOD
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    volumes:
      - /mnt/YOURFOLDER:/mnt:shared
    command: /usr/bin/s3fs -f -o allow_other -o use_cache=/tmp S3_BUCKET_NAME /mnt/
```

(no need for passwd files thx to s3fs understanding env variables)
